server {
    listen 80;
    listen [::]:80;
    server_name web.norenspring.com web.apex-springs.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location ^~ /wp-content/uploads/springapex-private/ {
        access_log off;
        return 404;
    }

    location / {
        return 301 https://web.norenspring.com$request_uri;
    }
}
